import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#767683",
        "on-surface": "#191c1d",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#151839",
        "on-secondary": "#ffffff",
        background: "#f8f9fa",
        "primary-fixed": "#e0e0ff",
        "surface-container-low": "#f3f4f5",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed": "#000767",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbd0",
        "error-container": "#ffdad6",
        secondary: "#585c80",
        "secondary-container": "#d2d4ff",
        "primary-fixed-dim": "#bdc2ff",
        "secondary-fixed": "#e0e0ff",
        primary: "#000666",
        "surface-variant": "#e1e3e4",
        "on-background": "#191c1d",
        "outline-variant": "#c6c5d4",
        "primary-container": "#1a237e",
        "on-tertiary-fixed": "#390c00",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#575b7f",
        "secondary-fixed-dim": "#c1c3ed",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-highest": "#e1e3e4",
        "inverse-primary": "#bdc2ff",
        "on-primary-container": "#8690ee",
        "tertiary-container": "#5c1800",
        "on-surface-variant": "#454652",
        "surface-dim": "#d9dadb",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#343d96",
        "on-tertiary-container": "#e17c5a",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb59d",
        "on-secondary-fixed-variant": "#414467",
        "on-tertiary-fixed-variant": "#7b2e12",
        tertiary: "#380b00",
        "surface-container": "#edeeef",
        "surface-tint": "#4c56af",
        surface: "#f8f9fa",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
};

export default config;
